openapi: "3.0.2"
info:
    title: Auth API
    version: "1.0"
servers:
    -   url: http://localhost:8080/
components:
    responses:
        UnauthorizedError:
            description: X-Ya-User-Ticket key is missing or invalid
    securitySchemes:
        UserTicketAuth:
            type: apiKey
            in: header
            name: X-Ya-User-Ticket
paths:
    /register:
        post:
            description: create new user
            security:
                - UserTicketAuth: [ ]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                login:
                                    type: string
                                password:
                                    type: string
                            required:
                                - login
                                - password
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: string
                '400':
                    description: invalid input data or user is already registered

    /login:
        post:
            description: login to system via credentials
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                login:
                                    type: string
                                password:
                                    type: string
                            required:
                                - login
                                - password
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: string
                '400':
                    description: invalid input data
                '404':
                    description: user not found or different password
    /check:
        post:
            description: check user's login uuid
            security:
                - UserTicketAuth: [ ]
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: string
                '401':
                    description: invalid login uuid