version: "2.3"

services:
    postgres:
        container_name: service-postgres
        image: postgres:12
        environment:
          - POSTGRES_DB=auth_db-1
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
        ports:
          - 5432
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
        networks:
          - postgres

    auth-service:
        build: ../
        image: auth-service-img
        privileged: true
        environment:
          - DYN_CONFIG_SERVER_ADRESS=http://10.21.0.234:8083/
          - POSTGRES_DB=auth_db-1
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - PREFIX=${PREFIX:-~/.local}
          - CC
          - CCACHE_DIR=/auth/.ccache
          - CCACHE_HASHDIR
          - CCACHE_NOHASHDIR
          - CCACHE_PREFIX
          - CCACHE_SIZE
          - CMAKE_OPTS
          - CORES_DIR=/cores
          - CXX
          - MAKE_OPTS
        volumes:
          - ..:/auth-volume:rw
          - ../third_party/userver/tools/docker:/tools:ro
          - ${TC_CORES_DIR:-../.cores}:/cores:rw
        ports:
          - 8080:8080
        working_dir: /auth
        depends_on:
          - postgres
        networks:
          - postgres

networks:
    postgres:
        driver: bridge
